swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

paths:
  /area:
    get:
      operationId: "area.read_all"
      tags:
        - Area
      description: "Read all geo areas"
      responses:
        200:
          description: "Successful read geo list operation"
          schema:
            type: "array"
            items:
              $ref: '#/definitions/area'
    put:
      operationId: "area.add"
      tags:
        - Area
      description: "Add a geo area"
      parameters:
        - in: body
          name: area
          description: "geo area to add"
          schema:
            $ref: '#/definitions/area'
      responses:
        200:
          description: "Successful add geo entry operation"
      
definitions:
    area:
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        area:
          type: "array"
          items:
            properties:
              longitude:
                type: "number"
              latitude:
                type: "number"
        country:
          type: "string"
        zip:
          type: "string"
        city:
          type: "string"
        region:
          type: "string"


