swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

paths:
  /area:
    get:
      operationId: "area.read_all"
      tags:
        - Area
      description: "Read all geo areas"
      responses:
        200:
          description: "Successful read geo list operation"
          schema:
            type: "array"
            items:
              $ref: '#/definitions/area'
    put:
      operationId: "area.add"
      tags:
        - Area
      description: "Add a geo area"
      parameters:
        - in: body
          name: area
          description: "geo area to add"
          schema:
            $ref: '#/definitions/area'
      responses:
        200:
          description: "Successful add geo entry operation"
  /source:
    get:
      operationId: "source.read_all"
      tags:
        - Source
      description: "Read all sources"
      responses:
        200:
          description: "Successful read source list operation"
          schema:
            type: "array"
            items:
              $ref: '#/definitions/source'
    put:
      operationId: "source.add"
      tags:
        - Source
      description: "Add a source"
      parameters:
        - in: body
          name: source
          description: "source to add"
          schema:
            $ref: '#/definitions/source'
      responses:
        200:
          description: "Successful add source operation"
  /cases:
    get:
      operationId: "cases.read_all"
      tags:
        - Cases
      description: "Read all cases"
      responses:
        200:
          description: "Successful read cases list operation"
          schema:
            type: "array"
            items:
              $ref: '#/definitions/cases'
    put:
      operationId: "cases.add"
      tags:
        - Cases
      description: "Add a cases entry"
      parameters:
        - in: body
          name: source
          description: "cases to add"
          schema:
            $ref: '#/definitions/cases'
      responses:
        200:
          description: "Successful add cases operation"
  
definitions:
    area:
      properties:
        id:
          type: "string"
        name:
          type: "string"
        area:
          type: "array"
          items:
            properties:
              longitude:
                type: "number"
              latitude:
                type: "number"
        country:
          type: "string"
        zip:
          type: "string"
        city:
          type: "string"
        region:
          type: "string"
    source:
      properties:
        id:
          type: "string"
        name:
          type: "string"
        url:
          type: "string"
    cases:
      properties:
        id:
          type: "string"
        date:
          type: "string"
        area:
          $ref: '#/definitions/area'
        infected:
          type: "integer"
        dead:
          type: "integer"
        recovered:
          type: "integer"
        source:
          $ref: '#/definitions/source'

