swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

paths:
  /source:
    get:
      operationId: "source.read_all"
      tags:
        - Source
      description: "Read all sources"
      responses:
        200:
          description: "Successful read source list operation"
          schema:
            type: "array"
            items:
              $ref: '#/definitions/source'
    put:
      operationId: "source.add"
      tags:
        - Source
      description: "Add a source"
      parameters:
        - in: body
          name: source
          description: "source to add"
          schema:
            $ref: '#/definitions/source'
      responses:
        200:
          description: "Successful add source operation"
  /cases:
    get:
      operationId: "cases.read_all"
      tags:
        - Cases
      description: "Read all cases"
      responses:
        200:
          description: "Successful read cases list operation"
          schema:
            type: "array"
            items:
              $ref: '#/definitions/cases'
    put:
      operationId: "cases.add"
      tags:
        - Cases
      description: "Add a cases entry"
      parameters:
        - in: body
          name: source
          description: "cases to add"
          schema:
            $ref: '#/definitions/cases'
      responses:
        200:
          description: "Successful add cases operation"
  
definitions:
    source:
      properties:
        _id:
          type: "string"
        name:
          type: "string"
        url:
          type: "string"
    cases:
      properties:
        _id:
          type: "string"
        date:
          type: "string"
        adm:
          type: "array"
          items:
            type: "string"
        ageRange:
          $ref: '#/definitions/ageRange'
        sex:
          type: "string"
        infected:
          type: "integer"
        dead:
          type: "integer"
        recovered:
          type: "integer"
        tested:
          type: "integer"
        source:
          type: "string"
    ageRange:
      properties:
        lower:
          type: "integer"
        upper:
          type: "integer"

